apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: superset
namespace: abhioncbr
resources:
- ../../base/
configMapGenerator:
- name: superset-config
  files:
  - https://raw.githubusercontent.com/abhioncbr/docker-superset/master/config/superset_config.py